# Generated by Django 5.0.2 on 2024-04-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellWatchin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(default=None, max_length=10)),
                ('age', models.IntegerField(max_length=4)),
                ('gender', models.CharField(default='M/F', max_length=10)),
                ('height', models.FloatField(max_length=4)),
                ('weight', models.FloatField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
