# Generated by Django 5.0.2 on 2024-04-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellWatchin', '0002_signup_delete_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='age',
            field=models.IntegerField(),
        ),
    ]
