# Generated by Django 5.0.2 on 2024-04-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellWatchin', '0003_alter_signup_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='bloodgroup',
            field=models.CharField(default=None, max_length=4),
        ),
    ]
