# Generated by Django 5.0.2 on 2024-04-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WellWatchin', '0006_signup_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
