# Generated by Django 5.0.2 on 2024-04-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WellWatchin', '0008_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='signupdetails',
        ),
    ]
