# Generated by Django 5.0.2 on 2024-04-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellWatchin', '0009_rename_signup_signupdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('username', models.CharField(default=None, max_length=20)),
                ('password', models.CharField(default=None, max_length=10)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(default='M/F', max_length=10)),
                ('height', models.FloatField(max_length=4)),
                ('weight', models.FloatField(max_length=4)),
                ('bloodgroup', models.CharField(default=None, max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='signupdetails',
        ),
    ]
