# Generated by Django 5.0.2 on 2024-04-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WellWatchin', '0011_alter_signup_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signup',
            table='wellwatchin_signup',
        ),
    ]
