# Generated by Django 5.0.2 on 2024-04-16 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WellWatchin', '0018_alter_signup_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='user',
        ),
    ]
