# Generated by Django 5.0.2 on 2024-04-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellWatchin', '0019_remove_signup_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('postalcode', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('extra', models.CharField(max_length=50)),
                ('feedback', models.CharField(max_length=40)),
            ],
        ),
    ]
