# Generated by Django 5.0.2 on 2024-04-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WellWatchin', '0020_profi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profi',
            new_name='Profile',
        ),
    ]
