# Generated by Django 5.0.2 on 2024-04-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WellWatchin', '0021_rename_profi_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='wellwatchin_profile',
        ),
    ]
