# Generated by Django 5.0.2 on 2024-04-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellWatchin', '0023_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
