# Generated by Django 5.0.2 on 2024-04-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellWatchin', '0024_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=20)),
                ('duration', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
