# Generated by Django 5.0.2 on 2024-04-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellWatchin', '0025_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='BP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=20)),
                ('sbp', models.CharField(max_length=4)),
                ('dbp', models.CharField(max_length=4)),
            ],
        ),
    ]
